### ISSUE TITLE
Filter GitHub Actions on  specific directory changes

### ISSUE THREAD

**Issue by antoinedelia** [antoinedelia/cloud-antoine-delia#1]
Currently, any commits will trigger GitHub Actions to deploy the whole infrastructure and the website, even if we just update something irrelevant (e.g: README.md)

We should check which files were updated in the last commit, and decide if we want to redeploy the infrastructure or the website.

https://github.com/antoinedelia/dentiste-auterive/blob/master/.github/workflows/main.yml

```
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          web:
            - 'web/**'
          terraform:
            - 'terraform/**'

    - name: Setup Terraform
      if: steps.filter.outputs.terraform == 'true'
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
```
